name: selenium-github-actions
on: 
  push:
  workflow_dispatch:
jobs:
  selenium:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Seleniumをインストールする！！！
        run: sudo pip3 install install selenium
      - name: 検温フォームを送る！！！！
        run: sudo python3 main.py